### ISSUE TITLE
VRP various improvements

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#45] opened 2023-06-28 14:53 UTC
- [x] timetable reference in `showError("Getting timetable has failed.", xhr);`
- [x] Show score next to solve button, so it's visible from any tab
- [ ] One-off issue with red visit even though 0 hard

![image](https://github.com/TimefoldAI/timefold-quickstarts/assets/176880/605eb33a-52ee-497a-b97a-e1fd60ee2e60)

- [x] navbar: non selected is hard to read
- [x] spacing under tab pills

![image](https://github.com/TimefoldAI/timefold-quickstarts/assets/176880/201f5a76-0ed0-4fb4-8339-0e3327b363d9)

**Comment by rsynek** [comment] 2023-07-03 08:53
spacing under tab pills addressed in:
https://github.com/TimefoldAI/timefold-quickstarts/pull/53

**Comment by zepfred** [comment] 2024-06-26 12:06
@ge0ffrey, I can't reproduce the issue `One-off issue with red visit even though 0 hard`.

**Comment by triceo** [comment] 2024-06-26 12:10
In two days, the issue will be 1 year old. Arguably, if something cannot be reproduced, it was already fixed in the meantime.

**Closed as completed** 2024-06-26 12:29 UTC
