### ISSUE TITLE
Bug: sourceVariableName for an InverseRelationShadowVariable cannot start with any letter after 'p'

### ISSUE THREAD

**Issue by trangd3** [TimefoldAI/timefold-quickstarts#315] opened 2024-02-29 17:06 UTC
**Describe the bug**
In the food-packaging example Job class, I renamed the Line variable to "technician", and updated the sourceVariableName for the startCleaningDateTime from "line" to "technician". Upon running, I received an error: "java.lang.NullPointerException: Cannot invoke "java.time.LocalDateTime.plus(java.time.temporal.TemporalAmount)" because "startCleaningDateTime" is null". After some digging, it seems that any name after 'p' gives me the same error, even if it is a random string. For example, "queue", "store", "xyz", "z", did not work. However, "previous", "dog", "cat", all worked.

**Expected behavior**
I should be able to use any variable name. 

**Actual behavior**
error: "java.lang.NullPointerException: Cannot invoke "java.time.LocalDateTime.plus(java.time.temporal.TemporalAmount)" because "startCleaningDateTime" is null"

**To Reproduce**
1. Rename Line variable in the Job class to anything that starts with a letter after 'p', such as "technician".
2. Update the sourceVariableName of the ShadowVariable decorator for startCleaningDateTime to be the same thing.
3. Update the getters and setters for that Line variable.
4. Run 'mvn quarkus:dev'

## Environment

**Timefold Solver Version or Git ref**: 
Timefold Solver Community Edition 1.7.0

**Output of `java -version`:**
java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

**Output of `uname -a` or `ver`:**
Microsoft Windows [Version 10.0.22621.3155]

## Additional information

Provide any and all other information which might be relevant to the issue.

**Comment by triceo** [comment] 2024-03-01 12:24
Thanks for reporting, @trangd3! We will take a look when time permits.

**Comment by triceo** [comment] 2024-03-04 19:32
We have solved the problem you reported @trangd3 by changing the variable listener.
The order of evaluation of shadow variables will be investigated in the solver; we need to confirm if this is the intended behavior, and if so, document it.

**Closed as completed by triceo** 2024-03-04 19:32 UTC
Labels: bug
